DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS reward CASCADE;

CREATE TABLE employee (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "type" VARCHAR(9) NOT NULL CHECK ("type" IN ('ADMIN', 'COLLECTOR')),
    username VARCHAR(50) NOT NULL,
    "password" VARCHAR(128) NOT NULL
);

CREATE TABLE "user" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "type" VARCHAR(9) NOT NULL CHECK ("type" IN ('SENDER', 'RECIPIENT')),
    username VARCHAR(50) NOT NULL,
    "password" VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    current_points INT NOT NULL DEFAULT 0,
    total_points INT NOT NULL DEFAULT 0
);

CREATE TABLE reward (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    points INTEGER NOT NULL,
    quantity_available INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false
);

INSERT INTO "user" (id, "type", "username", "password", email, cpf, current_points, total_points)
    VALUES 
        (50, 'SENDER', 'qwe', 'qwe', 'qwe@email.com', '00011122244', 850, 850),
        (51, 'SENDER', 'qwe2', 'qwe2', 'qwe2@email.com', '00011122255', 1, 200),
        (52, 'RECIPIENT', 'qwe3', 'qwe3', 'qwe3@email.com', '00001111222266', 1, 200);

INSERT INTO employee (id, "type", username, "password")
    VALUES 
        (50, 'ADMIN', 'admin', 'admin'),
        (51, 'COLLECTOR', 'collector', '123');

INSERT INTO reward (id, title, description, points, quantity_available)
    VALUES 
        (50, 'Ingresso show', 'Ingresso para o show da banda xyz.', 280, 5),
        (51, 'Bateria usada', 'Uma bela bateria usada.', 1, 999),
        (52, 'Ingresso cinema', 'Ingresso para o filme xyz.', 130, 999),
        (53, 'Ingresso cinema2', 'Ingresso para o filme xyz.', 357, 2),
        (54, 'Ingresso cinema3', 'Ingresso para o filme xyz.', 14, 4),
        (55, 'Ingresso cinema4', 'Ingresso para o filme xyz.', 99, 9);

UPDATE "user" SET username = 'qwe' WHERE id = 50;
UPDATE employee SET username = 'admin3' WHERE id = 52;
UPDATE "user" SET current_points = 1200, total_points = 9999 WHERE id = 5;

SELECT * FROM "user"
SELECT * FROM reward;
SELECT * FROM employee;
SELECT * FROM "user";