DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS reward CASCADE;
DROP TABLE IF EXISTS collection_point CASCADE;
DROP TABLE IF EXISTS waste_collection_request CASCADE;
DROP TABLE IF EXISTS waste_collection_request_recipient CASCADE;

CREATE TABLE employee (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "type" VARCHAR(9) NOT NULL CHECK ("type" IN ('ADMIN', 'COLLECTOR')),
    username VARCHAR(50) NOT NULL,
    "password" VARCHAR(128) NOT NULL,
    created_by BIGINT,
    is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE "user" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "type" VARCHAR(9) NOT NULL CHECK ("type" IN ('SENDER', 'RECIPIENT')),
    username VARCHAR(50) NOT NULL,
    "password" VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    current_points INT NOT NULL DEFAULT 0,
    total_points INT NOT NULL DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false
);

SELECT * FROM "user"

CREATE TABLE reward (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    points INTEGER NOT NULL,
    quantity_available INTEGER NOT NULL,
    is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE collection_point (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    capacity INTEGER,
    current_capacity INTEGER DEFAULT 0,
    longitude NUMERIC(10, 7),
    latitude NUMERIC(10, 7),
    request_date DATE DEFAULT CURRENT_DATE,
    approved BOOLEAN,
    sender_id BIGINT,
    is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE waste_collection_request (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    collection_point_id BIGINT,
    sender_id BIGINT,
    admin_id BIGINT,
    status VARCHAR(55),
    request_date DATE,
    scheduled_date DATE
)

CREATE TABLE waste_collection_request_recipient (
   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   request_id BIGINT,
   recipient_id BIGINT,
   is_deleted BOOLEAN DEFAULT false
)

SELECT * FROM waste_collection_request_recipient;
SELECT * FROM waste_collection_request;
SELECT * FROM collection_point;
SELECT * FROM employee;
SELECT * FROM "user";
SELECT * FROM reward;

SELECT * FROM waste_collection_request_recipient WHERE recipient_id = 52 AND request_id = 1

UPDATE "user" SET username = 'qwe10', "password" = 'qwe10' WHERE id = 52

UPDATE collection_point SET current_capacity = 99 WHERE id = 3


