DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS reward CASCADE;
DROP TABLE IF EXISTS collection_point CASCADE;

CREATE TABLE employee (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "type" VARCHAR(9) NOT NULL CHECK ("type" IN ('ADMIN', 'COLLECTOR')),
    username VARCHAR(50) NOT NULL,
    "password" VARCHAR(128) NOT NULL,
    created_by BIGINT,
    is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE "user" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "type" VARCHAR(9) NOT NULL CHECK ("type" IN ('SENDER', 'RECIPIENT')),
    username VARCHAR(50) NOT NULL,
    "password" VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    current_points INT NOT NULL DEFAULT 0,
    total_points INT NOT NULL DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE reward (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    points INTEGER NOT NULL,
    quantity_available INTEGER NOT NULL,
    is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE collection_point (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    capacity INTEGER,
    current_capacity INTEGER DEFAULT 0,
    longitude NUMERIC(10, 7),
    latitude NUMERIC(10, 7),
    request_date DATE DEFAULT CURRENT_DATE,
    approved BOOLEAN,
    sender_id BIGINT,
    is_deleted BOOLEAN DEFAULT false
);

SELECT * FROM collection_point;

-- CREATE TABLE collection_point_request (
--     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     sender_id BIGINT NOT NULL,
--     address VARCHAR(255) NOT NULL,
--     request_date DATE DEFAULT NOW(),
--     approved BOOLEAN DEFAULT FALSE,
--     longitude NUMERIC(10, 7),
--     latitude NUMERIC(10, 7)
-- );


SELECT * FROM employee;
SELECT * FROM "user";
SELECT * FROM reward;
